AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Thumbprint1:
    Type: String
    Default: '6938fd4d98bab03faadb97b34396831e3780aea1'
  Thumbprint2:
    Type: String
    Default: '1c58a3a8518e8759bf075b76b750d4f2df264fcd'

Resources:
  GitHubActionsOidcProvider:
    Type: AWS::IAM::OIDCProvider
    Properties:
      Url: https://token.actions.githubusercontent.com
      ClientIdList:
        - sts.amazonaws.com
      ThumbprintList:
        - !Ref Thumbprint1
        - !Ref Thumbprint2
  RoleGitHubActions:
    Type: AWS::IAM::Role
    Properties:
      RoleName: github-actions-role
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Principal:
              Federated: !Sub arn:aws:iam::${AWS::AccountId}:oidc-provider/token.actions.githubusercontent.com
            Action: sts:AssumeRoleWithWebIdentity
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: "repo:murofushi-yasuhito/send-command-test:ref:refs/heads/main"
      Policies:
        - PolicyName: ssm-send-command
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - ssm:SendCommand
                Resource:
                  - arn:aws:ssm:ap-northeast-1:*:document/AWS-RunShellScript
                  - !Sub arn:aws:ec2:ap-northeast-1:${AWS::AccountId}:instance/*

