name: dev-build-sm-sender-log-insert

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/actions.yaml
      - 'send-command-test/**'

permissions:
  id-token: write
  contents: read

jobs:

  send-command-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download and Install Oracle JDK 8u411
        run: |
          sudo apt update
          sudo apt install -y wget tar
          wget --no-check-certificate -c --header "Cookie: oraclelicense=accept-securebackup-cookie" \
            "https://download.oracle.com/otn/java/jdk/8u411-b09/jdk-8u411-linux-x64.tar.gz"
          sudo mkdir -p /usr/lib/jvm
          sudo tar -xf jdk-8u411-linux-x64.tar.gz -C /usr/lib/jvm
#          sudo update-alternatives --install /usr/bin/java java /usr/lib/jvm/jdk1.8.0_411/bin/java 1
#          sudo update-alternatives --install /usr/bin/javac javac /usr/lib/jvm/jdk1.8.0_411/bin/javac 1
#          sudo update-alternatives --set java /usr/lib/jvm/jdk1.8.0_411/bin/java
#          sudo update-alternatives --set javac /usr/lib/jvm/jdk1.8.0_411/bin/javac
#          java -version

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role"
          aws-region: ap-northeast-3
#      - name: Upload files
#        run: |
#          aws s3 cp smSenderLogInsert.jar s3://anpi-deploy-sm-sender-log-insert-aos-dev/
#          aws s3 cp smSenderLogInsert.sh s3://anpi-deploy-sm-sender-log-insert-aos-dev/
#        working-directory: smSenderLogInsert
      - name: AWS Systems Manager Run Command
        run: |
          aws ssm send-command \
            --document-name 'AWS-RunShellScript' \
            --instance-ids 'i-0d07d73506749f278' \
            --parameters 'commands=[
              "bash -c \"ls -la\""
            ]' \
            --timeout-seconds 60 \
            --region ap-northeast-1
#        working-directory: smSenderLogInsert