name: dev-build-sm-sender-log-insert

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/workflows/actions.yaml
      - 'send-command-test/**'

permissions:
  id-token: write
  contents: read

jobs:

  send-command-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: "arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/github-actions-role"
          aws-region: ap-northeast-3
      - name: AWS Systems Manager Run Command
        run: |
          aws ssm send-command \
            --document-name 'AWS-RunShellScript' \
            --instance-ids 'i-0d07d73506749f278' \
            --parameters 'commands=[
              "bash -c \"ls -la\""
            ]' \
            --timeout-seconds 60 \
            --region ap-northeast-1
#        working-directory: smSenderLogInsert